export const data = [
  {
    id: 1,
    image: require('../../images/fashion1.png'),
    text: 'Dresses',
    status: 'women',
  },
  {
    id: 2,
    image: require('../../images/fashion2.png'),
    text: 'Tops',
    status: 'women',
  },
  {
    id: 3,
    image: require('../../images/fashion3.png'),
    text: 'SportWare',
    status: 'women',
  },
  {
    id: 4,
    image: require('../../images/fashion1.png'),
    text: 'Dresses',
    status: 'women',
  },
  {
    id: 5,
    image: require('../../images/fashion2.png'),
    text: 'Tops',
    status: 'women',
  },
  {
    id: 6,
    image: require('../../images/fashion3.png'),
    text: 'SportWare',
    status: 'women',
  },
  {
    id: 7,
    image: require('../../images/fashion1.png'),
    text: 'Dresses',
    status: 'women',
  },
  {
    id: 8,
    image: require('../../images/fashion2.png'),
    text: 'Tops',
    status: 'women',
  },
  {
    id: 9,
    image: require('../../images/fashion3.png'),
    text: 'SportWare',
    status: 'women',
  },
  {
    id: 10,
    image: require('../../images/fashionm1.jpg'),
    text: 'Dresses',
    status: 'men',
  },
  {
    id: 11,
    image: require('../../images/fashionm2.jpg'),
    text: 'Tops',
    status: 'men',
  },
  {
    id: 12,
    image: require('../../images/fashionm3.jpg'),
    text: 'SportWare',
    status: 'men',
  },
  {
    id: 13,
    image: require('../../images/fashionm1.jpg'),
    text: 'Dresses',
    status: 'men',
  },
  {
    id: 14,
    image: require('../../images/fashionm2.jpg'),
    text: 'Tops',
    status: 'men',
  },
  {
    id: 15,
    image: require('../../images/fashionm3.jpg'),
    text: 'SportWare',
    status: 'men',
  },
  {
    id: 16,
    image: require('../../images/fashionm1.jpg'),
    text: 'Dresses',
    status: 'men',
  },
  {
    id: 17,
    image: require('../../images/fashionm2.jpg'),
    text: 'Tops',
    status: 'men',
  },
  {
    id: 18,
    image: require('../../images/fashionm3.jpg'),
    text: 'SportWare',
    status: 'men',
  },
  {
    id: 19,
    image: require('../../images/fashionk1.jpg'),
    text: 'Dresses',
    status: 'kids',
  },
  {
    id: 20,
    image: require('../../images/fashionk2.jpg'),
    text: 'Tops',
    status: 'kids',
  },
  {
    id: 21,
    image: require('../../images/fashionk3.jpg'),
    text: 'SportWare',
    status: 'kids',
  },
  {
    id: 22,
    image: require('../../images/fashionk1.jpg'),
    text: 'Dresses',
    status: 'kids',
  },
  {
    id: 23,
    image: require('../../images/fashionk2.jpg'),
    text: 'Tops',
    status: 'kids',
  },
  {
    id: 24,
    image: require('../../images/fashionk3.jpg'),
    text: 'SportWare',
    status: 'kids',
  },
  {
    id: 25,
    image: require('../../images/fashionk1.jpg'),
    text: 'Dresses',
    status: 'kids',
  },
  {
    id: 26,
    image: require('../../images/fashionk2.jpg'),
    text: 'Tops',
    status: 'kids',
  },
  {
    id: 27,
    image: require('../../images/fashionk3.jpg'),
    text: 'SportWare',
    status: 'kids',
  },
];
